# Generated by Django 4.2.5 on 2024-07-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kerusakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('definisi', models.TextField()),
                ('solusi', models.TextField()),
                ('gambar', models.ImageField(null=True, upload_to='kerusakan/')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BasisPengetahuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.FloatField()),
                ('kode_gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorapp.gejala')),
                ('kode_kerusakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorapp.kerusakan')),
            ],
        ),
    ]
