# Generated by Django 4.2.5 on 2024-07-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kerusakan',
            old_name='definisi',
            new_name='deskripsi',
        ),
    ]
