# Generated by Django 4.2.5 on 2024-08-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorapp', '0002_rename_definisi_kerusakan_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_gejala', models.TextField()),
                ('kerusakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorapp.kerusakan')),
            ],
        ),
    ]
