# Generated by Django 4.2.5 on 2024-08-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorapp', '0003_datakasus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tgl', models.DateTimeField()),
                ('result', models.TextField()),
            ],
        ),
    ]
