# Generated by Django 4.2.5 on 2024-08-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorapp', '0004_riwayat'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakasus',
            name='hasil',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
